<?php
/**
 * Suburb page data.
 *
 * Replaces 35 `computer-repairs-*` templates that were 83% identical to each
 * other (97% at worst) and 14 `postcode-*` pages that duplicated ten of them
 * outright. Google classifies that pattern as doorway pages.
 *
 * Ten primaries remain. Every absorbed suburb is covered as a real section on
 * its primary page and 301s there, so long-tail coverage survives without the
 * thin-content penalty.
 *
 * Generated by tools/build-locations.py — edit the source data there.
 */

/** Primary suburb pages, keyed by URL slug (/computer-repairs-{slug}). */
function rt_locations(): array
{
    return [
        'cranbourne' => [
            'suburb'      => 'Cranbourne',
            'postcode'    => '3977',
            'lat'         => '-38.0996',
            'lng'         => '145.2834',
            'population'  => '21,000',
            'distance'    => '5',
            'blurb'       => 'Same-day computer repairs and IT support across Cranbourne 3977 and the surrounding growth corridor. We are based here, so callouts are fast.',
            'landmarks'   => [
                'Cranbourne Park Shopping Centre',
                'Royal Botanic Gardens Cranbourne',
                'Casey Fields',
                'Cranbourne Racecourse',
                'Cranbourne Station',
            ],
            'covers'      => [
                'Clyde',
                'Clyde North',
                'Botanic Ridge',
                'Junction Village',
                'Devon Meadows',
                'Lynbrook',
                'Lyndhurst',
                'Sandhurst',
            ],
            'neighbours'  => [
                'narre-warren',
                'berwick',
                'dandenong',
                'carrum-downs',
            ],
            'issues'      => [
                'home office setups',
                'small business networks',
                'new-estate NBN connections',
                'gaming PC builds',
            ],
            'absorbs'     => [
                'cranbourne-east',
                'cranbourne-north',
                'cranbourne-west',
                'botanic-ridge',
                'junction-village',
                'devon-meadows',
                'sandhurst',
                'clyde',
                'clyde-north',
                'lynbrook',
                'lyndhurst',
            ],
            'body'        => <<<'HTML'
<h2>Your Local Computer Repair Team in Cranbourne</h2>
<p>Rapid Tech Solutions is based in Cranbourne South, which makes Cranbourne and the
surrounding 3977 postcode our home ground. Most callouts here are reached within
fifteen minutes, and the majority of jobs are completed the same day. We work with
households, home offices and small businesses right across the area &mdash; from the
established streets near Cranbourne Park Shopping Centre to the newer estates pushing
south toward Botanic Ridge.</p>

<h3>Computer Repairs for Cranbourne&rsquo;s Growth Corridor</h3>
<p>Cranbourne has grown quickly, and a lot of that growth is new housing. New estates
bring a specific set of technology problems: NBN connections that were provisioned before
anyone moved in, Wi-Fi that cannot cover a double-storey house on a narrow block, and
home offices set up in a hurry. We handle all of it &mdash; connection troubleshooting,
mesh Wi-Fi that actually reaches the back bedroom, and workstation setups that hold up to
a full working week.</p>

<h3>Clyde, Clyde North and Botanic Ridge</h3>
<p>The estates through Clyde, Clyde North and Botanic Ridge are some of the fastest-growing
in Victoria, and they are all within our standard callout range. If you have just moved in
and your internet has never worked properly, or the builder&rsquo;s data cabling was never
finished off, that is a job we do regularly.</p>

<h3>Junction Village, Devon Meadows and Sandhurst</h3>
<p>These smaller pockets around Cranbourne are easy to overlook, and larger repair chains
often will not travel to them. We do. Whether it is a slow family desktop in Junction
Village, a rural-block Wi-Fi problem in Devon Meadows, or a home office in Sandhurst, the
callout rate is the same as anywhere else in 3977.</p>

<h3>Lynbrook and Lyndhurst</h3>
<p>Lynbrook and Lyndhurst sit between Cranbourne and Dandenong, and we cover both as part
of our regular run. Common jobs here are laptop screen replacements, virus and malware
clean-ups, and upgrading older machines to SSDs to get a few more years out of them.</p>
HTML,
        ],
        'berwick' => [
            'suburb'      => 'Berwick',
            'postcode'    => '3806',
            'lat'         => '-38.0333',
            'lng'         => '145.3453',
            'population'  => '50,000',
            'distance'    => '12',
            'blurb'       => 'Computer repairs and IT support throughout Berwick 3806. Same-day onsite service for homes, home offices and local businesses.',
            'landmarks'   => [
                'Berwick Village',
                'Eden Rise Village',
                'Federation University Berwick',
                'Casey Hospital',
                'Wilson Botanic Park',
            ],
            'covers'      => [
                'Beaconsfield',
                'Officer',
                'Narre Warren',
                'Harkaway',
                'Clyde North',
            ],
            'neighbours'  => [
                'narre-warren',
                'cranbourne',
                'dandenong',
            ],
            'issues'      => [
                'professional home offices',
                'medical practice IT',
                'student laptop repairs',
                'small business servers',
            ],
            'absorbs'     => [
            ],
            'body'        => <<<'HTML'
<h2>Computer Repairs and IT Support in Berwick</h2>
<p>Berwick is one of the larger centres in Melbourne&rsquo;s south-east, and the mix of
work here reflects that. Alongside ordinary household repairs we do a lot of home-office
and small-business work &mdash; the sort of setups where a day of downtime actually costs
something. We carry common replacement parts, so laptop screens, drives and memory can
usually be sorted in a single visit.</p>

<h3>Home Offices and Professional Services</h3>
<p>Berwick has a high proportion of residents working from home or running a practice from
a consulting suite. That means reliable backups, secure remote access and a network that
does not drop out mid-call. We set up and maintain all three, and we will document what we
have done so you are not dependent on us to understand your own system.</p>

<h3>Students and Family Machines</h3>
<p>With Federation University&rsquo;s Berwick campus and a large number of schools in the
area, student laptops are a steady part of our work. Cracked screens, failed batteries,
liquid damage and machines that have simply slowed to a crawl are all routine. Where a
repair is not economic we will tell you that rather than quote for it.</p>

<h3>Wilson Botanic Park to Eden Rise</h3>
<p>Berwick&rsquo;s older streets around the Village and Wilson Botanic Park often have
solid brick construction that Wi-Fi struggles with, while the newer estates out toward
Eden Rise have the opposite problem &mdash; large floor plans on small blocks. Both need a
different approach to coverage, and a single router in the study rarely solves either.</p>
HTML,
        ],
        'narre-warren' => [
            'suburb'      => 'Narre Warren',
            'postcode'    => '3805',
            'lat'         => '-38.0264',
            'lng'         => '145.3050',
            'population'  => '28,000',
            'distance'    => '14',
            'blurb'       => 'Fast computer repairs across Narre Warren 3805, Narre Warren South and Hampton Park. Onsite and workshop service available.',
            'landmarks'   => [
                'Westfield Fountain Gate',
                'Bunjil Place',
                'Casey Central',
                'Narre Warren Station',
                'Sweeney Reserve',
            ],
            'covers'      => [
                'Narre Warren South',
                'Hampton Park',
                'Fountain Gate',
                'Berwick',
                'Hallam',
            ],
            'neighbours'  => [
                'berwick',
                'cranbourne',
                'dandenong',
            ],
            'issues'      => [
                'retail point-of-sale systems',
                'family computer repairs',
                'small business networks',
                'Wi-Fi blackspots',
            ],
            'absorbs'     => [
                'narre-warren-south',
                'hampton-park',
            ],
            'body'        => <<<'HTML'
<h2>Computer Repairs in Narre Warren</h2>
<p>Narre Warren is a busy commercial centre as much as a residential one, and Westfield
Fountain Gate anchors a large amount of local retail and small business. We work on both
sides of that &mdash; family desktops and laptops during the day, and business systems
outside trading hours where downtime matters.</p>

<h3>Narre Warren South</h3>
<p>Narre Warren South is largely newer housing on generous blocks, and the single most
common call we get from the area is Wi-Fi that will not reach the far end of the house.
A mesh system properly placed usually fixes it permanently; adding a cheap extender
usually does not, and we will say so.</p>

<h3>Hampton Park</h3>
<p>Hampton Park sits between Narre Warren and Dandenong and is well within our regular
run. Typical work here is virus and malware removal, slow-machine diagnostics, and getting
older computers running usefully again with an SSD and a memory upgrade rather than
replacing them outright.</p>

<h3>Business Support Around Fountain Gate</h3>
<p>Retail and hospitality around Fountain Gate and Casey Central depend on point-of-sale
systems, card terminals and a network that stays up through the busiest part of the day.
We handle network design, failover connections and the kind of preventative maintenance
that stops a trading day being lost.</p>
HTML,
        ],
        'dandenong' => [
            'suburb'      => 'Dandenong',
            'postcode'    => '3175',
            'lat'         => '-37.9877',
            'lng'         => '145.2145',
            'population'  => '30,000',
            'distance'    => '15',
            'blurb'       => 'Computer repairs and business IT support in Dandenong 3175, Noble Park, Keysborough and Springvale. Same-day onsite service.',
            'landmarks'   => [
                'Dandenong Market',
                'Dandenong Plaza',
                'Drum Theatre',
                'Dandenong Station',
                'Greater Dandenong Council Offices',
            ],
            'covers'      => [
                'Noble Park',
                'Keysborough',
                'Springvale',
                'Dandenong North',
                'Bangholme',
            ],
            'neighbours'  => [
                'narre-warren',
                'cranbourne',
                'mordialloc',
                'chelsea',
            ],
            'issues'      => [
                'manufacturing and warehouse IT',
                'retail systems',
                'multilingual support',
                'small business networks',
            ],
            'absorbs'     => [
                'noble-park',
                'keysborough',
                'springvale',
            ],
            'body'        => <<<'HTML'
<h2>IT Excellence for Dandenong's Commercial Hub</h2>
        <p>As one of Melbourne's most significant regional centres, Dandenong serves as the economic heart of the south-eastern corridor. The revitalized CBD, anchored by Dandenong Plaza and the vibrant Dandenong Market, attracts thousands of visitors daily. This commercial intensity demands robust IT infrastructure, and that's exactly what we deliver.</p>

        <h3>Retail Technology for Dandenong's Shopping Precinct</h3>
        <p>Dandenong Plaza and the surrounding retail areas house major national chains alongside independent retailers. Each requires seamless point-of-sale operations, secure payment processing, and reliable inventory management. We've partnered with numerous Plaza retailers to implement cloud-based POS systems, train staff on cybersecurity best practices, and ensure business continuity during system updates.</p>

        <h3>Supporting Dandenong's Manufacturing Sector</h3>
        <p>The industrial areas of Dandenong South and West house some of Victoria's most important manufacturing facilities. These operations require specialised IT support—from SCADA system security to network infrastructure connecting production floors with management offices. We understand that downtime costs thousands per hour, so our industrial clients receive priority response times and proactive monitoring.</p>

        <h3>Government and Institutional IT Services</h3>
        <p>As a major regional centre, Dandenong hosts government offices, educational institutions, and healthcare facilities. These organisations require IT partners who understand compliance requirements, data security protocols, and system reliability. We've supported local government departments with secure remote access solutions and helped educational institutions implement learning management systems.</p>

        <h3>Small Business IT Partnership</h3>
        <p>The Afghan Bazaar, Little India precinct, and multicultural food businesses along Foster Street represent entrepreneurial spirit. We help these small businesses compete with larger retailers by implementing affordable technology solutions—from social media-integrated ordering systems to customer loyalty programs. Our multilingual support ensures language is never a barrier to excellent IT service.</p>
<h3>Noble Park</h3>
<p>Noble Park is a short run from Dandenong and we cover it on the same callout schedule.
The housing stock is a mix of established homes and newer townhouses, and the most common
jobs are network setups, virus removal and recovering data from drives that have started
to fail.</p>

<h3>Keysborough</h3>
<p>Keysborough combines large residential estates with a substantial industrial and
warehousing area along the Eastlink corridor. That means two very different kinds of work:
home Wi-Fi and family machines on one side, and business networks, shared storage and
backup systems on the other. We do both.</p>

<h3>Springvale</h3>
<p>Springvale has a dense retail strip and a large number of small owner-operated
businesses. Point-of-sale reliability, secure card processing and simple, dependable
backups matter more here than anything elaborate, and that is what we set up.</p>
HTML,
        ],
        'frankston' => [
            'suburb'      => 'Frankston',
            'postcode'    => '3199',
            'lat'         => '-38.1431',
            'lng'         => '145.1228',
            'population'  => '36,000',
            'distance'    => '12',
            'blurb'       => 'Computer repairs and IT support across Frankston 3199, Frankston North, Langwarrin and Pearcedale. Same-day onsite service available.',
            'landmarks'   => [
                'Frankston Pier',
                'Bayside Shopping Centre',
                'Frankston Hospital',
                'Frankston Arts Centre',
                'Frankston Waterfront',
            ],
            'covers'      => [
                'Frankston South',
                'Frankston North',
                'Langwarrin',
                'Karingal',
                'Pearcedale',
            ],
            'neighbours'  => [
                'seaford',
                'carrum-downs',
                'patterson-lakes',
            ],
            'issues'      => [
                'healthcare practice IT',
                'retail systems',
                'professional services',
                'home offices',
            ],
            'absorbs'     => [
                'langwarrin',
                'pearcedale',
            ],
            'body'        => <<<'HTML'
<h2>Regional IT Excellence for Frankston</h2>
        <p>As the gateway to the Mornington Peninsula and a major regional center, Frankston serves as the commercial, healthcare, and cultural hub for Melbourne's southeastern corridor. The city's ongoing revitalization has transformed the waterfront and CBD into vibrant destinations, attracting businesses and residents who need reliable, professional IT support that matches Frankston's growing sophistication.</p>

        <h3>Healthcare IT for Frankston's Medical Hub</h3>
        <p>Frankston Hospital and the numerous medical practices throughout the city create significant healthcare IT requirements. We provide HIPAA-compliant solutions for medical practices, ensure patient data remains secure, and maintain systems that healthcare providers depend on for patient care. Our understanding of healthcare IT compliance makes us the trusted partner for Frankston's medical community. From GP clinics to specialist practices, we ensure technology supports rather than hinders patient care.</p>

        <h3>Retail Technology for Bayside Shopping Centre</h3>
        <p>Bayside Shopping Centre anchors Frankston's retail sector, housing major retailers and local businesses. These operations require seamless point-of-sale systems, secure payment processing, and networks that handle high customer volumes. We've supported numerous Bayside retailers with technology solutions that improve efficiency and customer experience. Our responsive support means technical issues don't translate to lost sales during busy periods.</p>

        <h3>Professional Services IT</h3>
        <p>Frankston's CBD hosts accountants, lawyers, financial advisors, and other professional services. These businesses require IT systems that maintain client confidentiality while enabling efficient operations. We implement secure document management systems, configure compliant backup solutions, and provide ongoing support that keeps professional services operating smoothly. Our understanding of various industry compliance requirements makes us the ideal IT partner for Frankston professionals.</p>

        <h3>Educational Institution Support</h3>
        <p>Frankston features excellent educational institutions including Monash University Peninsula Campus, Chisholm TAFE, and numerous schools. These institutions require specialised IT support—from campus-wide networks to learning management systems and student device management. We've worked with educational organizations to modernize their IT infrastructure while maintaining security and enabling effective learning environments.</p>

        <h3>Hospitality and Tourism Technology</h3>
        <p>The revitalized Frankston Waterfront and surrounding restaurants, cafes, and bars attract visitors from across Melbourne. These hospitality businesses need technology that enhances customer experience—from efficient reservation systems to customer WiFi and modern payment processing. We support Frankston's hospitality sector with technology solutions that handle busy periods and create memorable customer experiences.</p>

        <h3>Residential Technology Services</h3>
        <p>Frankston's diverse residential areas—from waterfront apartments to established family homes—require varied IT solutions. We provide home network optimization, smart home installations, security systems, and computer repairs that meet diverse residential needs. Our technicians understand different housing types and provide customised solutions that work for Frankston's varied housing stock.</p>

        <h3>Community and Arts Technology</h3>
        <p>Frankston Arts Centre and various community organizations rely on technology to serve their audiences. We've supported arts organizations with ticketing systems, community groups with membership management, and local organizations with technology that enables their missions. Our commitment to Frankston extends beyond commercial services—we believe in supporting the cultural and community fabric that makes the city vibrant.</p>
<h3>Frankston North</h3>
<p>Frankston North is covered on the same terms as the rest of Frankston, with no
additional callout charge. Most work here is straightforward repair and clean-up
&mdash; slow machines, malware, failing drives and getting older hardware running well
enough to be worth keeping.</p>

<h3>Langwarrin</h3>
<p>Langwarrin&rsquo;s larger blocks and single-storey homes spread out further than a
standard router will cover, and it is one of the more common places we install mesh Wi-Fi.
We also do a steady amount of home-office work here for people commuting into Frankston or
working remotely.</p>

<h3>Pearcedale</h3>
<p>Pearcedale is semi-rural and often falls outside the range other technicians will
travel. It does not fall outside ours. Rural-block internet, satellite and fixed-wireless
troubleshooting, and long-run cabling between house and shed are all regular jobs.</p>
HTML,
        ],
        'carrum-downs' => [
            'suburb'      => 'Carrum Downs',
            'postcode'    => '3201',
            'lat'         => '-38.0908',
            'lng'         => '145.1707',
            'population'  => '23,000',
            'distance'    => '10',
            'blurb'       => 'Computer repairs and business IT support in Carrum Downs 3201 and Skye. Onsite service for homes and the local industrial estate.',
            'landmarks'   => [
                'Carrum Downs Shopping Centre',
                'Ballam Park',
                'Carrum Downs Industrial Estate',
                'Peninsula Link',
                'Banyan Fields',
            ],
            'covers'      => [
                'Skye',
                'Seaford',
                'Frankston North',
                'Langwarrin',
                'Sandhurst',
            ],
            'neighbours'  => [
                'seaford',
                'frankston',
                'patterson-lakes',
                'cranbourne',
            ],
            'issues'      => [
                'warehouse and light industrial IT',
                'home offices',
                'small business networks',
                'point-of-sale systems',
            ],
            'absorbs'     => [
                'skye',
            ],
            'body'        => <<<'HTML'
<h2>IT Solutions for Carrum Downs' Rapid Growth</h2>
        <p>Carrum Downs is one of Melbourne's fastest-growing suburbs, attracting young families, first-home buyers, and businesses seeking strategic locations. The suburb combines new residential estates with established areas and a significant industrial precinct. This dynamic growth creates diverse IT needs that require a technology partner who understands both modern residential requirements and commercial operations—exactly what we provide.</p>

        <h3>New Estate Technology Setup</h3>
        <p>Carrum Downs' numerous new housing estates often have brand-new homes requiring complete technology setup. We help new homeowners from the ground up—from configuring NBN connections in newly built homes to installing smart home systems, setting up security cameras, and creating whole-house WiFi coverage. Our experience with new constructions means we understand how to optimise technology in modern open-plan homes with their specific challenges and opportunities.</p>

        <h3>Young Family Technology Solutions</h3>
        <p>Many Carrum Downs residents are young families establishing their first homes. We provide technology solutions that grow with these families—from baby monitoring systems to educational computers and gaming setups as children grow. Our affordable approach respects young family budgets while ensuring they have reliable technology. We explain things clearly, understanding that not everyone is tech-savvy, and provide ongoing support as needs evolve.</p>

        <h3>Industrial Area Business IT</h3>
        <p>The Ballarto Road industrial area houses warehouses, manufacturing facilities, and trade businesses. These operations require robust IT infrastructure—from inventory management systems to fleet tracking and secure business networks. We've supported numerous Carrum Downs businesses with solutions that improve efficiency and enable growth. Our understanding of small to medium business needs means we recommend practical solutions that deliver results without excessive costs.</p>

        <h3>Trade Business Technology</h3>
        <p>Many Carrum Downs residents run trade businesses—electricians, plumbers, builders, and landscapers. These businesses increasingly rely on technology for job management, invoicing, and customer communication. We help tradies implement mobile-friendly solutions that work in the field, set up cloud accounting systems, and configure devices for reliable operation. Our practical approach means technology helps rather than hinders their work.</p>

        <h3>Retail Support for Carrum Downs Shopping Centre</h3>
        <p>Carrum Downs Shopping Centre and the surrounding retail areas serve as the community's commercial hub. Local retailers need reliable point-of-sale systems, inventory management, and customer WiFi. We support these businesses with responsive IT services that understand retail challenges—from handling busy periods to ensuring secure payment processing. Our local presence means we respond quickly when issues arise.</p>

        <h3>Community Facility Technology</h3>
        <p>The Lyrebird Community Centre, recreation reserves, and local sporting clubs rely on technology to serve residents. We've helped community organizations modernize their operations with membership management systems, booking platforms, and communication tools. Our commitment to Carrum Downs includes supporting the facilities that bring the community together and enhance quality of life.</p>

        <h3>Future-Proofing Growing Families</h3>
        <p>As Carrum Downs families grow and evolve, their technology needs change. We provide scalable solutions that adapt—from adding devices to existing networks to upgrading systems as children become teenagers with different requirements. Our long-term approach means we're partners in your technology journey, not just one-time service providers.</p>
<h3>Skye</h3>
<p>Skye sits directly alongside Carrum Downs and is covered on the same callout run. It is
mostly newer residential estates, and the recurring issues are the ones that come with new
builds &mdash; NBN connections that were never properly commissioned, patchy Wi-Fi across
a two-storey floor plan, and home offices that need to work reliably from day one.</p>
HTML,
        ],
        'seaford' => [
            'suburb'      => 'Seaford',
            'postcode'    => '3198',
            'lat'         => '-38.1044',
            'lng'         => '145.1290',
            'population'  => '17,000',
            'distance'    => '9',
            'blurb'       => 'Computer repairs and IT support in Seaford 3198. Same-day onsite service for homes and businesses along the bayside strip.',
            'landmarks'   => [
                'Seaford Beach',
                'Seaford Wetlands',
                'Seaford Station',
                'Nepean Highway shops',
                'Belvedere Reserve',
            ],
            'covers'      => [
                'Carrum',
                'Frankston North',
                'Carrum Downs',
                'Bonbeach',
                'Patterson Lakes',
            ],
            'neighbours'  => [
                'carrum-downs',
                'frankston',
                'patterson-lakes',
                'chelsea',
            ],
            'issues'      => [
                'coastal corrosion on hardware',
                'home offices',
                'small business networks',
                'Wi-Fi coverage',
            ],
            'absorbs'     => [
            ],
            'body'        => <<<'HTML'
<h2>Growing with Seaford's Thriving Community</h2>
        <p>Seaford has transformed into one of Melbourne's most desirable family suburbs, combining beach lifestyle with affordability and excellent amenities. The suburb features a mix of established neighborhoods near the beach and newer developments further inland. This growth creates diverse IT needs, from supporting young families to enabling home businesses—challenges we're well-equipped to handle.</p>

        <h3>Supporting Seaford's Young Families</h3>
        <p>Seaford attracts young families drawn by affordable housing, excellent schools, and beach lifestyle. These families need technology that grows with them—from baby monitors and smart home security to gaming setups for teenagers and homework computers. We provide flexible IT support that adapts to changing family needs, offering affordable solutions that don't strain family budgets. Our technicians are friendly and patient, explaining technology in terms everyone understands.</p>

        <h3>New Development Connectivity</h3>
        <p>Seaford's newer estates often face unique connectivity challenges as infrastructure catches up with development. We specialise in optimising NBN connections in these areas, recommending appropriate equipment, and configuring networks for maximum performance. Whether you're in Seaford North or the newer areas near Seaford Meadows, we ensure your technology performs optimally despite potential infrastructure limitations.</p>

        <h3>Home Business Technology</h3>
        <p>Many Seaford residents run home-based businesses—from tradies managing jobs to creative professionals and online retailers. We provide professional-grade home business solutions including secure networks, reliable backup systems, and equipment that supports business operations. Our understanding of small business needs means we recommend practical, cost-effective solutions rather than expensive enterprise systems.</p>

        <h3>Seaford Shopping Centre Business Support</h3>
        <p>The Seaford Shopping Centre and surrounding retail areas serve as the commercial heart of the suburb. Local businesses need reliable point-of-sale systems, secure payment processing, and networks that handle customer traffic. We support these businesses with responsive IT services, understanding that downtime directly impacts their livelihood. Our fast response times mean technical issues don't translate to lost customers.</p>

        <h3>Environmental Technology</h3>
        <p>Seaford's beautiful wetlands and environmental consciousness inspire residents to embrace eco-friendly technology. We help with solar monitoring systems, energy management automation, and smart home technology that reduces environmental impact. Our solutions align with the community's values while delivering practical benefits through reduced energy costs and improved home efficiency.</p>

        <h3>Beach and Lifestyle Technology</h3>
        <p>The iconic Seaford Pier and beautiful beaches define life here. We provide technology that enhances this lifestyle—from waterproof speakers for beach gatherings to security systems that protect homes while families enjoy the water. Our solutions are designed for the Seaford way of life, providing connectivity and security without complicated systems that detract from beach enjoyment.</p>
HTML,
        ],
        'patterson-lakes' => [
            'suburb'      => 'Patterson Lakes',
            'postcode'    => '3197',
            'lat'         => '-38.0714',
            'lng'         => '145.1310',
            'population'  => '8,000',
            'distance'    => '8',
            'blurb'       => 'Computer repairs and IT support in Patterson Lakes 3197, Carrum and Bonbeach. Onsite service across the waterway estates.',
            'landmarks'   => [
                'Patterson Lakes Marina',
                'Patterson River',
                'Thompson Road shops',
                'Carrum Station',
                'Launching Way',
            ],
            'covers'      => [
                'Carrum',
                'Bonbeach',
                'Chelsea',
                'Seaford',
                'Bangholme',
            ],
            'neighbours'  => [
                'chelsea',
                'seaford',
                'carrum-downs',
                'mordialloc',
            ],
            'issues'      => [
                'waterfront property Wi-Fi',
                'home offices',
                'marine business IT',
                'network coverage across large blocks',
            ],
            'absorbs'     => [
                'carrum',
                'bonbeach',
            ],
            'body'        => <<<'HTML'
<h2>Computer Repairs in Patterson Lakes</h2>
<p>Patterson Lakes is built around its waterways, and that geography creates network
problems you do not see elsewhere. Homes are often long and narrow, frequently
double-storey, and many have a separate studio, boatshed or garage across the property that
still needs to be on the network. A single router in the living room does not cover it.</p>

<h3>Waterfront and Marina Properties</h3>
<p>Properties along the canals and around the marina regularly need coverage extended out
to a jetty, deck or detached workspace. We install mesh systems and, where the run is too
long for wireless, we cable it properly. Salt air is also hard on hardware &mdash;
connectors corrode and fans clog faster here than a few kilometres inland &mdash; so
preventative cleaning is worth more in this area than most.</p>

<h3>Carrum</h3>
<p>Carrum sits just across the river and is covered on the same callout run. Work here is a
mix of family machines, holiday-home setups and small businesses along the Nepean Highway
strip. Station-precinct redevelopment has brought a wave of newer apartments, which come
with their own set of connection and coverage questions.</p>

<h3>Bonbeach</h3>
<p>Bonbeach is a narrow strip between the railway line and the beach, largely established
housing with a growing number of townhouses. Typical jobs are Wi-Fi coverage, virus and
malware clean-ups, data recovery from failing drives, and getting older desktops usefully
fast again rather than replacing them.</p>
HTML,
        ],
        'chelsea' => [
            'suburb'      => 'Chelsea',
            'postcode'    => '3196',
            'lat'         => '-38.0522',
            'lng'         => '145.1178',
            'population'  => '7,500',
            'distance'    => '12',
            'blurb'       => 'Computer repairs and IT support in Chelsea 3196, Chelsea Heights, Edithvale and Aspendale. Same-day onsite service for homes and businesses.',
            'landmarks'   => [
                'Chelsea Beach',
                'Chelsea Station',
                'Station Street shops',
                'Bicentennial Park',
                'Chelsea RSL',
            ],
            'covers'      => [
                'Chelsea Heights',
                'Edithvale',
                'Aspendale',
                'Bonbeach',
                'Carrum',
            ],
            'neighbours'  => [
                'patterson-lakes',
                'mordialloc',
                'seaford',
            ],
            'issues'      => [
                'coastal humidity and hardware',
                'home offices',
                'retail point-of-sale',
                'Wi-Fi coverage in older homes',
            ],
            'absorbs'     => [
                'chelsea-heights',
                'edithvale',
                'aspendale',
            ],
            'body'        => <<<'HTML'
<h2>Computer Repairs Along the Chelsea Bayside Strip</h2>
<p>Chelsea and its neighbours are among the older parts of the bayside strip, and the
housing stock shows it &mdash; solid double-brick homes, a lot of renovations, and
increasingly townhouses squeezed onto subdivided blocks. All three make Wi-Fi harder than
the floor area suggests, and it is the single most common reason we get called out here.</p>

<h3>Chelsea Heights</h3>
<p>Chelsea Heights sits back from the water on larger blocks, with a mix of established
family homes and newer builds. Alongside the usual repair work we do a steady amount of
home-office setup here &mdash; proper backups, secure remote access and a network that
holds up to a full day of video calls.</p>

<h3>Edithvale</h3>
<p>Edithvale is a narrow strip between the beach and the wetlands, mostly established
housing. Salt air is a genuine factor: it corrodes connectors and shortens the life of
cooling fans, so machines here benefit from cleaning and inspection more often than
inland. We also handle the usual run of virus removal, drive failures and slow-machine
diagnostics.</p>

<h3>Aspendale</h3>
<p>Aspendale combines beachfront homes with the retail strip along Station Street. We work
with both &mdash; residential repairs and Wi-Fi on one side, and point-of-sale, card
terminals and small business networks on the other.</p>
HTML,
        ],
        'mordialloc' => [
            'suburb'      => 'Mordialloc',
            'postcode'    => '3195',
            'lat'         => '-38.0053',
            'lng'         => '145.0876',
            'population'  => '8,000',
            'distance'    => '16',
            'blurb'       => 'Computer repairs and IT support in Mordialloc 3195, Mentone, Cheltenham and Beaumaris. Onsite service for homes and Main Street businesses.',
            'landmarks'   => [
                'Mordialloc Pier',
                'Main Street Mordialloc',
                'Mordialloc Creek',
                'Braeside Park',
                'Mordialloc Station',
            ],
            'covers'      => [
                'Mentone',
                'Aspendale',
                'Braeside',
                'Cheltenham',
                'Beaumaris',
            ],
            'neighbours'  => [
                'chelsea',
                'patterson-lakes',
                'dandenong',
            ],
            'issues'      => [
                'hospitality and retail systems',
                'home offices',
                'professional practices',
                'Wi-Fi in period homes',
            ],
            'absorbs'     => [
                'mentone',
            ],
            'body'        => <<<'HTML'
<h2>Diverse IT Solutions Across the 3195 Postcode</h2>
        <p>The 3195 postcode encompasses three distinct areas—coastal Mordialloc and Aspendale, and industrial Braeside. This diversity requires IT providers who understand varied needs, from waterfront hospitality to manufacturing operations. Our experience across these different environments makes us the ideal technology partner for residents and businesses throughout 3195.</p>

        <h3>Hospitality IT for Mordialloc's Restaurant Precinct</h3>
        <p>Mordialloc's dining scene centers around the famous pier and creek, with restaurants and cafes attracting visitors from across Melbourne. These hospitality businesses require reliable technology—from reservation systems to payment processing and kitchen management. We've helped Mordialloc restaurants implement efficient POS systems, set up outdoor WiFi for alfresco dining, and ensured payment systems handle busy periods without failure. Our rapid response means technical issues don't ruin service during peak times.</p>

        <h3>Industrial IT for Braeside Business Park</h3>
        <p>Braeside houses numerous warehouses, manufacturing facilities, and distribution centers. These operations require robust IT infrastructure that supports inventory management, logistics tracking, and production monitoring. We've implemented warehouse management systems, configured multi-site networks for businesses with multiple Braeside locations, and ensured security systems protect valuable inventory. Our understanding of industrial IT requirements makes us the trusted partner for Braeside businesses.</p>

        <h3>Waterfront Property Technology</h3>
        <p>Aspendale and Mordialloc feature beautiful waterfront properties with unique technology challenges. Coastal conditions require special considerations—from equipment that withstands salt air to networks designed for properties with water views that might interfere with signals. We specialise in these installations, ensuring waterfront homes enjoy reliable connectivity without compromising the views they were designed to showcase.</p>

        <h3>Marina and Boating Technology</h3>
        <p>With Mordialloc Yacht Club and numerous boat owners in the area, marine technology support is increasingly important. We assist with onshore connectivity for vessels, help boat owners sync navigation systems with home networks, and provide technical support for marine electronics. Our knowledge extends from traditional IT to specialised marine applications.</p>

        <h3>Residential Support Across 3195</h3>
        <p>Whether you live in a weatherboard cottage in Mordialloc, a modern home in Aspendale, or near Braeside Park, we provide consistent, reliable home IT support. From NBN optimization to home security systems and family computer repairs, our technicians deliver friendly, professional service that meets the diverse needs of 3195 residents.</p>

        <h3>Community Technology Initiatives</h3>
        <p>We actively support local community organizations including sporting clubs, community centers, and environmental groups managing Braeside Park. Our commitment to 3195 extends beyond commercial services—we believe technology should strengthen community connections and support local initiatives that make this postcode special.</p>
<h3>Mentone</h3>
<p>Mentone has a large stock of period homes, and solid brick walls are consistently the
reason Wi-Fi underperforms there. Extending coverage properly usually means a mesh system
with a wired backhaul rather than another repeater. We also see a steady stream of laptop
repairs and data recovery from the area&rsquo;s schools and home offices.</p>

<h3>Cheltenham and Beaumaris</h3>
<p>Cheltenham&rsquo;s retail and commercial precinct and Beaumaris&rsquo;s largely
residential streets are both within our regular run. Business work around Cheltenham tends
toward point-of-sale and small office networks; Beaumaris is mostly residential repairs,
Wi-Fi coverage across large blocks, and backup setups for people working from home.</p>
HTML,
        ],
    ];
}

/**
 * 301 map: retired suburb/postcode slug => canonical destination path.
 * Mirrored in the web-root .htaccess so the redirect happens before PHP runs.
 */
function rt_location_redirects(): array
{
    return [
        'computer-repairs-aspendale' => '/computer-repairs-chelsea/',
        'computer-repairs-bonbeach' => '/computer-repairs-patterson-lakes/',
        'computer-repairs-botanic-ridge' => '/computer-repairs-cranbourne/',
        'computer-repairs-carrum' => '/computer-repairs-patterson-lakes/',
        'computer-repairs-chelsea-heights' => '/computer-repairs-chelsea/',
        'computer-repairs-clyde' => '/computer-repairs-cranbourne/',
        'computer-repairs-clyde-north' => '/computer-repairs-cranbourne/',
        'computer-repairs-cranbourne-east' => '/computer-repairs-cranbourne/',
        'computer-repairs-cranbourne-north' => '/computer-repairs-cranbourne/',
        'computer-repairs-cranbourne-west' => '/computer-repairs-cranbourne/',
        'computer-repairs-devon-meadows' => '/computer-repairs-cranbourne/',
        'computer-repairs-edithvale' => '/computer-repairs-chelsea/',
        'computer-repairs-hampton-park' => '/computer-repairs-narre-warren/',
        'computer-repairs-junction-village' => '/computer-repairs-cranbourne/',
        'computer-repairs-keysborough' => '/computer-repairs-dandenong/',
        'computer-repairs-langwarrin' => '/computer-repairs-frankston/',
        'computer-repairs-lynbrook' => '/computer-repairs-cranbourne/',
        'computer-repairs-lyndhurst' => '/computer-repairs-cranbourne/',
        'computer-repairs-mentone' => '/computer-repairs-mordialloc/',
        'computer-repairs-narre-warren-south' => '/computer-repairs-narre-warren/',
        'computer-repairs-noble-park' => '/computer-repairs-dandenong/',
        'computer-repairs-pearcedale' => '/computer-repairs-frankston/',
        'computer-repairs-sandhurst' => '/computer-repairs-cranbourne/',
        'computer-repairs-skye' => '/computer-repairs-carrum-downs/',
        'computer-repairs-springvale' => '/computer-repairs-dandenong/',
        'page-privacy' => '/privacy-policy/',
        'postcode-3152' => '/service-areas/',
        'postcode-3173' => '/computer-repairs-dandenong/',
        'postcode-3174' => '/computer-repairs-dandenong/',
        'postcode-3175' => '/computer-repairs-dandenong/',
        'postcode-3178' => '/service-areas/',
        'postcode-3192' => '/computer-repairs-mordialloc/',
        'postcode-3193' => '/computer-repairs-mordialloc/',
        'postcode-3194' => '/computer-repairs-mordialloc/',
        'postcode-3195' => '/computer-repairs-mordialloc/',
        'postcode-3196' => '/computer-repairs-patterson-lakes/',
        'postcode-3198' => '/computer-repairs-seaford/',
        'postcode-3199' => '/computer-repairs-frankston/',
        'postcode-3200' => '/computer-repairs-frankston/',
        'postcode-3201' => '/computer-repairs-carrum-downs/',
        'service-area' => '/service-areas/',
    ];
}

/**
 * Canonical path for a suburb name, following consolidation.
 * Used for internal links so nothing points at a redirected URL.
 */
function rt_location_path(string $suburb): ?string
{
    static $index = null;

    if ($index === null) {
        $index = [];
        foreach (rt_locations() as $slug => $loc) {
            $index[strtolower($loc['suburb'])] = '/computer-repairs-' . $slug . '/';
            foreach ($loc['absorbs'] as $a) {
                $index[str_replace('-', ' ', $a)] = '/computer-repairs-' . $slug . '/';
            }
        }
    }

    return $index[strtolower(trim($suburb))] ?? null;
}

/** Total distinct suburbs served: 10 primaries + absorbed localities. */
function rt_suburb_count(): int
{
    static $n = null;
    if ($n === null) {
        $absorbed = [];
        foreach (rt_locations() as $loc) {
            foreach ($loc['absorbs'] as $a) {
                $absorbed[] = $a;
            }
        }
        $n = count(rt_locations()) + count(array_unique($absorbed));
    }
    return $n;
}
